name: 'Apply latest configuration to Fleet'

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
  - cron: '0 6 * * *'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

defaults:
  run:
    shell: bash

permissions:
  contents: read
  id-token: write

jobs:
  fleet-gitops:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitOps repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::959713283180:role/GitHubActions-fleet-gitops
          aws-region: us-east-2

      - name: Fetch secrets from AWS using ARNs
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            FLEET_API_TOKEN, ${{ secrets.FLEET_API_TOKEN_ARN }}
            FLEET_GLOBAL_ENROLL_SECRET, ${{ secrets.FLEET_GLOBAL_ENROLL_SECRET_ARN }}
            FLEET_WORKSTATIONS_ENROLL_SECRET, ${{ secrets.FLEET_WORKSTATIONS_ENROLL_SECRET_ARN }}
            FLEET_DEDICATED_DEVICES_ENROLL_SECRET, ${{ secrets.FLEET_DEDICATED_DEVICES_ENROLL_SECRET_ARN }}
            FLEET_IT_SERVERS_ENROLL_SECRET, ${{ secrets.FLEET_IT_SERVERS_ENROLL_SECRET_ARN }}
            FLEET_EMPLOYEE_ISSUED_MOBILE_DEVICES_ENROLL_SECRET, ${{ secrets.FLEET_EMPLOYEE_ISSUED_MOBILE_DEVICES_ENROLL_SECRET_ARN }}
            FLEET_PERSONAL_MOBILE_DEVICES_ENROLL_SECRET, ${{ secrets.FLEET_PERSONAL_MOBILE_DEVICES_ENROLL_SECRET_ARN }}
          parse-json-secrets: false

      - name: Apply latest configuration to Fleet
        uses: ./.github/gitops-action
        with:
          dry-run-only: ${{ github.event_name == 'pull_request' && 'true' || 'false' }}
        env:
          FLEET_URL: ${{ secrets.FLEET_URL }}
          FLEET_API_TOKEN: ${{ env.FLEET_API_TOKEN }}
          FLEET_GLOBAL_ENROLL_SECRET: ${{ env.FLEET_GLOBAL_ENROLL_SECRET }}
          FLEET_WORKSTATIONS_ENROLL_SECRET: ${{ env.FLEET_WORKSTATIONS_ENROLL_SECRET }}
          FLEET_DEDICATED_DEVICES_ENROLL_SECRET: ${{ env.FLEET_DEDICATED_DEVICES_ENROLL_SECRET }}
          FLEET_IT_SERVERS_ENROLL_SECRET: ${{ env.FLEET_IT_SERVERS_ENROLL_SECRET }}
          FLEET_EMPLOYEE_ISSUED_MOBILE_DEVICES_ENROLL_SECRET: ${{ env.FLEET_EMPLOYEE_ISSUED_MOBILE_DEVICES_ENROLL_SECRET }}
          FLEET_PERSONAL_MOBILE_DEVICES_ENROLL_SECRET: ${{ env.FLEET_PERSONAL_MOBILE_DEVICES_ENROLL_SECRET }}
